/*
 * This file is generated by jOOQ.
 */
package com.slj.springplaymvn.codegen;


import com.slj.springplaymvn.codegen.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpringPlay extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>spring_play</code>
     */
    public static final SpringPlay SPRING_PLAY = new SpringPlay();

    /**
     * 用户信息表
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private SpringPlay() {
        super("spring_play", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            User.USER);
    }
}
