/*
 * This file is generated by jOOQ.
 */
package com.slj.springplaymvn.codegen;


import com.slj.springplaymvn.codegen.tables.User;


/**
 * Convenience access to all tables in spring_play.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 用户信息表
     */
    public static final User USER = User.USER;
}
